version: '3.8'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./rag/pdfs:/app/rag/pdfs
      - ./data:/app/data
      - ./rag/faiss_index.bin:/app/rag/faiss_index.bin
      - ./rag/embeddings.pkl:/app/rag/embeddings.pkl
      - ./documents.db:/app/documents.db
    restart: unless-stopped
