services:
  - type: web
    name: rag-document-system
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: rag-storage
      mountPath: /opt/render/project/src/rag
      sizeGB: 1
